#!/bin/bash
# OpenCode + WorkBuddy 完整重建脚本
# 系统崩溃后，在新系统上执行此脚本恢复所有配置
set -e
echo "=== 重建步骤 ==="
echo ""
echo "1) git clone <你的仓库URL> ~/OpencodeWorkspace"
echo "   cd ~/OpencodeWorkspace"
echo ""
echo "2) 安装基础依赖"
echo "   npm install -g opencode"
echo "   pip3 install requests markdown python-pptx pillow"
echo ""
echo "3) 恢复OpenCode配置"
echo "   cp _rebuild/opencode.jsonc.template ~/.config/opencode/opencode.jsonc"
echo "   编辑 ~/.config/opencode/opencode.jsonc 填入真实API密钥"
echo ""
echo "4) 安装MCP依赖"
echo "   npx -y @cyanheads/secedgar-mcp-server"
echo "   npx -y yfinance-mcp"
echo "   npx -y fred-mcp-server"
echo "   npm install -g ppt-mcp"
echo "   npx -y @modelcontextprotocol/server-filesystem"
echo ""
echo "5) 恢复公众号凭证"
echo "   cp _rebuild/.env.template scripts/.env"
echo "   编辑 scripts/.env 填入真实AppID和AppSecret"
echo ""
echo "6) 恢复共享大脑"
echo "   mkdir -p ~/.workbuddy/shared-workspace"
echo "   cp -r _rebuild/shared-brain/* ~/.workbuddy/shared-workspace/"
echo ""
echo "7) 验证"
echo "   bash ~/.workbuddy/shared-workspace/scripts/verify-setup.sh"
echo ""
echo "8) 启动"
echo "   opencode"
echo "   输入 '继续' 恢复工作上下文"
